import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { Provider } from "./providers";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        {/* the entire application is wrapped with client provider */}
        <Provider> 
          <Navbar />
          <main className="max-w-screen-lg flex flex-wrap items-center justify-between mx-auto">
            {children}
          </main>
        </Provider>
      </body>  
    </html>
  );
}
